// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_int from "rescript/lib/es6/js_int.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_SetString from "rescript/lib/es6/belt_SetString.js";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

var MalformedInput = /* @__PURE__ */Caml_exceptions.create("Solution06.MalformedInput");

function solve(message, extraCount) {
  var indexes = Belt_Array.range(0, message.length);
  var target = Belt_Array.getBy(indexes, (function (idx) {
          return Js_int.equal(Belt_SetString.size(Belt_SetString.fromArray(message.slice(idx, idx + extraCount | 0).split(""))), extraCount);
        }));
  if (target !== undefined) {
    return target + extraCount | 0;
  }
  throw {
        RE_EXN_ID: MalformedInput,
        Error: new Error()
      };
}

function solve1(__x) {
  return solve(__x, 4);
}

function solve2(__x) {
  return solve(__x, 14);
}

export {
  MalformedInput ,
  solve ,
  solve1 ,
  solve2 ,
}
/* No side effect */
